---
- name: VECTOR | Ensure group "vector" exists
  ansible.builtin.group:
    name: "{{ vector_group }}"
    state: present

- name: VECTOR | Add the user 'vector' with a bash shell, appending the group 'vector' and groups for scraping
  ansible.builtin.user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"
    groups: "{{ vector_groups | default('') }}"
    shell: /usr/sbin/nologin
    createhome: no
    append: True

- name: VECTOR | Install the Vector rpm from a remote repo
  ansible.builtin.yum:
    name: "https://yum.vector.dev/stable/vector-0/{{ ansible_architecture }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    state: present
  when: ansible_os_family == RedHat
  notify: restart service

- name: VECTOR | Install the Vector deb from a remote repo
  ansible.builtin.apt:
    deb: "https://apt.vector.dev/pool/v/ve/vector_{{ vector_version }}-1_{{ deb_architecture[ansible_architecture] }}.deb"
    state: present
  when: ansible_os_family == Debian