---
- name: INSTALL | Ensure group "vector" exists
  become: true
  become_method: su
  ansible.builtin.group:
    name: "{{ vector_group }}"
    state: present

- name: INSTALL | Add the user 'vector' with a bash shell, appending the group 'vector' and groups for scraping
  become: true
  become_method: su
  ansible.builtin.user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"
    groups: "{{ vector_groups | default('') }}"
    shell: /usr/sbin/nologin
    createhome: true
    append: true

- name: INSTALL | Install Vector rpm from a remote repo (yum)
  become: true
  become_method: su
  ansible.builtin.yum:
    name: "https://yum.vector.dev/stable/vector-0/{{ ansible_architecture }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    state: present
  notify: restart vector
  when: ansible_pkg_mgr == "yum"

- name: INSTALL | Install Vector deb from a remote repo (apt)
  become: true
  become_method: su
  ansible.builtin.apt:
    deb: "https://apt.vector.dev/pool/v/ve/vector_{{ vector_version }}-1_{{ deb_architecture[ansible_architecture] }}.deb"
    state: present
  notify: restart vector
  when: ansible_pkg_mgr == "apt"

- name: INSTALL | Install Vector rpm from a remote repo (dnf)
  become: true
  become_method: su
  when: ansible_pkg_mgr == "dnf"
  block:
    - name: INSTALL | mirror fix one
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^mirrorlist(.*)?$'
        replace: '# mirrorlist\1'
      loop: "{{ lookup('ansible.builtin.fileglob', '/etc/yum.repos.d/*') }}"

    - name: INSTALL | mirror fix two
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^#baseurl=http://mirror.centos.org(.*)?$'
        replace: 'baseurl=http://vault.centos.org\1'
      loop: "{{ lookup('ansible.builtin.fileglob', '/etc/yum.repos.d/*') }}"

#     - name: INSTALL | dnf fix mirrors
#       ansible.builtin.replace:
#         path: "{{ item.path }}"
#         regexp: "{{ item.regexp }}"
#         replace: "{{ item.replace }}"
#       loop:
#         - { path: "{{ q('fileglob', '/etc/yum.repos.d/*') }}", regexp: '^mirrorlist(.*)?$', replace: '# mirrorlist\1' }
#         - { path: "{{ q('fileglob', '/etc/yum.repos.d/*') }}", regexp: '^#baseurl=http://mirror.centos.org(.*)?$', replace: 'baseurl=http://vault.centos.org\1' }

    - name: INSTALL | Install Vector
      ansible.builtin.yum:
        name: "https://yum.vector.dev/stable/vector-0/{{ ansible_architecture }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
        state: present
      notify: restart vector
