---
- name: INSTALL | Ensure group "vector" exists
  become: true
  become_method: ansible.builtin.su
  ansible.builtin.group:
    name: "{{ role_vector_group }}"
    state: present
  tags: [install]

- name: INSTALL | Add the user 'vector' with a bash shell, appending the group 'vector' and groups for scraping
  become: true
  become_method: ansible.builtin.su
  ansible.builtin.user:
    name: "{{ role_vector_user }}"
    group: "{{ role_vector_group }}"
    groups: "{{ role_vector_groups | default('') }}"
    shell: /usr/sbin/nologin
    create_home: true
    append: true
  tags: [install]

- name: INSTALL | Install distr from repo
  ansible.builtin.include_tasks:
    file: "{{ lookup('first_found', params) }}"
    apply:
      tags: [install]
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
        - 'empty.yml'
  tags: [install]

- name: CONFIG | Set Vector config from template
  ansible.builtin.template:
    src: "{{ role_vector_config_template }}"
    dest: /etc/vector/vector.yaml
    mode: '0755'
  notify: reload vector
  tags: [configure]

- name: CONFIG | Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: [configure]
