---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/shared/collections.yml
    role-file: molecule/shared/requirements.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint .
platforms:

  - name: ubuntu_vector
    groups:
      - vectors
    image: ubuntu:22.04
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init

  - name: centos_8_vector
    groups:
      - vectors
    image: centos:8
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

  - name: centos_7_vector
    groups:
      - vectors
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify:  ../shared/verify.yml
verifier:
  name: ansible
