---
# dependency:
#   name: galaxy
#   options:
#     requirements-file: collections.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint .
platforms:

  - name: ubuntu
    groups:
      - vectors
    image: ubuntu:latest
    dockerfile: ./Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init

  - name: centos_8
    groups:
      - vectors
    image: centos:8
    dockerfile: ./Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

  - name: centos_7
    groups:
      - vectors
    image: centos:7
    dockerfile: ./Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

provisioner:
  name: ansible
verifier:
  name: ansible
