---
- name: Verify
  hosts: vectors
  tasks:
    - name: Get Service Status
      ansible.builtin.systemd:
        name: vector
      register: vector_service

    - ansible.builtin.debug:
        var: vector_service.status.ActiveState

    - name: Check Vector API (GET /health status 200)
      ansible.builtin.uri:
        url: "http://0.0.0.0:{{ role_vector_port }}/health"
      vars:
        role_vector_port: 8686