---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/shared/collections.yml
    role-file: molecule/shared/requirements.yml
driver:
  name: podman
lint: |
  set -e
  ansible-lint . --exclude ./.tox/ --exclude ./.git/
platforms:

  - name: ubuntu_vector
    groups:
      - vectors
    image: ubuntu:22.04
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify:  ../shared/verify.yml
verifier:
  name: ansible
